// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `asset_class` table.
    ///
    /// (Automatically generated by Diesel.)
    asset_class (code) {
        /// The `code` column of the `asset_class` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Text,
    }
}

diesel::table! {
    /// Representation of the `asset_coverage_bitmap` table.
    ///
    /// (Automatically generated by Diesel.)
    asset_coverage_bitmap (id) {
        /// The `id` column of the `asset_coverage_bitmap` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `manifest_id` column of the `asset_coverage_bitmap` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        manifest_id -> Integer,
        /// The `bitmap` column of the `asset_coverage_bitmap` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        bitmap -> Binary,
        /// The `version` column of the `asset_coverage_bitmap` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

diesel::table! {
    /// Representation of the `asset_gaps` table.
    ///
    /// (Automatically generated by Diesel.)
    asset_gaps (id) {
        /// The `id` column of the `asset_gaps` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `manifest_id` column of the `asset_gaps` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        manifest_id -> Integer,
        /// The `start_ts` column of the `asset_gaps` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        start_ts -> Text,
        /// The `end_ts` column of the `asset_gaps` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        end_ts -> Text,
        /// The `state` column of the `asset_gaps` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        state -> Text,
        /// The `lease_owner` column of the `asset_gaps` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        lease_owner -> Nullable<Text>,
        /// The `lease_expires_at` column of the `asset_gaps` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        lease_expires_at -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `asset_manifest` table.
    ///
    /// (Automatically generated by Diesel.)
    asset_manifest (id) {
        /// The `id` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `symbol` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        symbol -> Text,
        /// The `provider` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        provider -> Text,
        /// The `asset_class` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        asset_class -> Text,
        /// The `timeframe_amount` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        timeframe_amount -> Integer,
        /// The `timeframe_unit` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        timeframe_unit -> Text,
        /// The `desired_start` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        desired_start -> Text,
        /// The `desired_end` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        desired_end -> Nullable<Text>,
        /// The `watermark` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        watermark -> Nullable<Text>,
        /// The `last_error` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        last_error -> Nullable<Text>,
        /// The `created_at` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `updated_at` column of the `asset_manifest` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Text,
    }
}

diesel::table! {
    /// Representation of the `engine_kv` table.
    ///
    /// (Automatically generated by Diesel.)
    engine_kv (k) {
        /// The `k` column of the `engine_kv` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        k -> Nullable<Text>,
        /// The `v` column of the `engine_kv` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        v -> Text,
    }
}

diesel::table! {
    /// Representation of the `provider` table.
    ///
    /// (Automatically generated by Diesel.)
    provider (code) {
        /// The `code` column of the `provider` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Text,
        /// The `name` column of the `provider` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}

diesel::table! {
    /// Representation of the `provider_asset_class` table.
    ///
    /// (Automatically generated by Diesel.)
    provider_asset_class (provider_code, asset_class_code) {
        /// The `provider_code` column of the `provider_asset_class` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        provider_code -> Text,
        /// The `asset_class_code` column of the `provider_asset_class` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        asset_class_code -> Text,
    }
}

diesel::table! {
    /// Representation of the `provider_symbol_map` table.
    ///
    /// (Automatically generated by Diesel.)
    provider_symbol_map (provider_code, asset_class_code, canonical_symbol) {
        /// The `provider_code` column of the `provider_symbol_map` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        provider_code -> Text,
        /// The `asset_class_code` column of the `provider_symbol_map` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        asset_class_code -> Text,
        /// The `canonical_symbol` column of the `provider_symbol_map` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        canonical_symbol -> Text,
        /// The `remote_symbol` column of the `provider_symbol_map` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        remote_symbol -> Text,
    }
}

diesel::joinable!(asset_coverage_bitmap -> asset_manifest (manifest_id));
diesel::joinable!(asset_gaps -> asset_manifest (manifest_id));
diesel::joinable!(provider_asset_class -> asset_class (asset_class_code));
diesel::joinable!(provider_asset_class -> provider (provider_code));

diesel::allow_tables_to_appear_in_same_query!(
    asset_class,
    asset_coverage_bitmap,
    asset_gaps,
    asset_manifest,
    engine_kv,
    provider,
    provider_asset_class,
    provider_symbol_map,
);
