
services:
  spark-master:
    image: docker.io/bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      # - "4040:4040"  # Spark application web UI
      - "8080:8080"  # Spark master web UI
      - "7077:7077"  # Spark master port
    # environment:
    #   - SPARK_MODE=master
    #   - SPARK_MASTER_HOST=spark-master
    #   - SPARK_LOCAL_IP=spark-master

    # volumes:
    #   - ./data/master:/opt/spark/data  # Mount a directory for the master's data access
    networks:
      - spark-network


  spark-worker:
    image: docker.io/bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2

    # volumes:
    #   - ./data/worker:/opt/spark/data  # Mount a directory for the worker's data access
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    
