# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
with_docs = true
filter = { only_tables = ["asset_manifest", "asset_coverage_bitmap", "asset_gaps"] }
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "migrations"
