[workspace]
# No workspace-wide version bump

[package.market_data_ingestor]
post-release-hook = ["git", "cliff", "-c", "market_data_ingestor/cliff.toml", "--include-path", "src/market_data_ingestor/**", "-p", "/market_data_ingestor/CHANGELOG.md", "--latest"]


[package.storage_service]
pre-release-hook = ["git", "cliff", "-c", "storage_service/cliff.toml", "--include-path", "src/storage_service/**", "-p", "/storage_service/CHANGELOG.md", "--latest"]
