[workspace]
# No workspace-wide version bump

[package.market_data_ingestor]
post-release-hook = ["git", "cliff", "--include-path", "src/market_data_ingestor/**", "-p", "src/market_data_ingestor/CHANGELOG.md", "--latest", "--template-package", "market_data_ingestor"]


[package.storage_service]
pre-release-hook = ["git", "cliff", "--include-path", "src/storage_service/**", "-p", "src/storage_service/CHANGELOG.md", "--latest", "--template-package", "storage_service"]
