[workspace]
# No workspace-wide version bump

[package.market_data_ingestor]
post-release-hook = ["git", "cliff", "-w", "/home/hanbo/repo/stock_trading_bot/",  "-c", "src/market_data_ingestor/cliff.toml", "--include-path", "src/market_data_ingestor/**", "-p", "src/market_data_ingestor/CHANGELOG.md", "--latest"]


[package.storage_service]
pre-release-hook = ["git", "cliff", "-w", "/home/hanbo/repo/stock_trading_bot/", "-c", "src/storage_service/cliff.toml", "--include-path", "src/storage_service/**", "-p", "src/storage_service/CHANGELOG.md", "--latest"]
