[changelog]
header = """
# Changelog
All notable changes to market_data_ingestor will be documented in this file.
"""
body = """
{% if version %}## {{ version }}{% if date %} ({{ date }}){% endif %}{% else %}## [Latest]{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/mag1cfrog/stock_trading_bot/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^chore\\(release\\):", skip = true },
  { message = "^chore", group = "Maintenance" }
]