
services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    build: spark/
    networks:
      iceberg_net:
    depends_on:
      - rest
      - minio
    volumes:
      - "/home/iceberg/spark-events:/home/iceberg/spark-events"
      - ./data/warehouse:/home/iceberg/warehouse
      - ./notebooks/iceberg:/home/iceberg/notebooks/notebooks
      # - ./extra-jars/iceberg-spark-runtime-0.13.2.jar:/opt/spark/jars/iceberg-spark-runtime-0.13.2.jar
      # - ./extra-jars:/opt/spark/extra-jars  # Mount the directory with the AWS SDK jar
      - ./extra-jars:/tmp/extra-jars
      - ./scripts/copy-jars.sh:/opt/spark/copy-jars.sh
      - ./scripts/spark_job.py:/opt/spark/work-dir/spark_job.py
    entrypoint: ["/bin/sh", "/opt/spark/copy-jars.sh"]
    command: ["spark-submit", "/opt/spark/work-dir/spark_job.py"]
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - SPARK_EXTRA_CLASSPATH=/opt/spark/extra-jars/*
    ports:
      - 7077:7077 # Spark master port
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
    
  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
networks:
  iceberg_net: