name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
  workflow_dispatch: {}   # manual run

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    env:
      MARKET_DATA_INGESTOR_SKIP_PYTHON_SETUP: "1"
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src -> target
      
      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --workspace --all-features -- -D warnings

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      
      - name: test
        run: cargo nextest run --workspace --all-features --no-fail-fast
